$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: diabetes-endpoint
model:
  path: ../model
  type: custom_model
code_configuration:
  code: .
  scoring_script: score.py
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
  conda_file: environment.yml
instance_type: Standard_D2as_v4
instance_count: 1
data_collector:
  collections:
    model_inputs:
      enabled: 'true'
    model_outputs:
      enabled: 'true'
