$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: diabetes-deploy-env
version: 1
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file:
  channels:
    - defaults
  dependencies:
    - python=3.8
    - pip:
      - mlflow==1.30.0
      - cloudpickle==2.2.0
      - scikit-learn==0.24.1
      - azureml-inference-server-http
      - numpy
